export enum Card {
  BLANK_CARD = 'BLANK_CARD',
  //  Spades
  SPADES_ACE = 'SPADES_ACE',
  SPADES_TWO = 'SPADES_TWO',
  SPADES_THREE = 'SPADES_THREE',
  SPADES_FOUR = 'SPADES_FOUR',
  SPADES_FIVE = 'SPADES_FIVE',
  SPADES_SIX = 'SPADES_SIX',
  SPADES_SEVEN = 'SPADES_SEVEN',
  SPADES_EIGHT = 'SPADES_EIGHT',
  SPADES_NINE = 'SPADES_NINE',
  SPADES_TEN = 'SPADES_TEN',
  SPADES_JACK = 'SPADES_JACK',
  SPADES_QUEEN = 'SPADES_QUEEN',
  SPADES_KING = 'SPADES_KING',
  // Hearts
  HEARTS_ACE = 'HEARTS_ACE',
  HEARTS_TWO = 'HEARTS_TWO',
  HEARTS_THREE = 'HEARTS_THREE',
  HEARTS_FOUR = 'HEARTS_FOUR',
  HEARTS_FIVE = 'HEARTS_FIVE',
  HEARTS_SIX = 'HEARTS_SIX',
  HEARTS_SEVEN = 'HEARTS_SEVEN',
  HEARTS_EIGHT = 'HEARTS_EIGHT',
  HEARTS_NINE = 'HEARTS_NINE',
  HEARTS_TEN = 'HEARTS_TEN',
  HEARTS_JACK = 'HEARTS_JACK',
  HEARTS_QUEEN = 'HEARTS_QUEEN',
  HEARTS_KING = 'HEARTS_KING',
  // Diamonds
  DIAMONDS_ACE = 'DIAMONDS_ACE',
  DIAMONDS_TWO = 'DIAMONDS_TWO',
  DIAMONDS_THREE = 'DIAMONDS_THREE',
  DIAMONDS_FOUR = 'DIAMONDS_FOUR',
  DIAMONDS_FIVE = 'DIAMONDS_FIVE',
  DIAMONDS_SIX = 'DIAMONDS_SIX',
  DIAMONDS_SEVEN = 'DIAMONDS_SEVEN',
  DIAMONDS_EIGHT = 'DIAMONDS_EIGHT',
  DIAMONDS_NINE = 'DIAMONDS_NINE',
  DIAMONDS_TEN = 'DIAMONDS_TEN',
  DIAMONDS_JACK = 'DIAMONDS_JACK',
  DIAMONDS_QUEEN = 'DIAMONDS_QUEEN',
  DIAMONDS_KING = 'DIAMONDS_KING',
  // Clubs
  CLUBS_ACE = 'CLUBS_ACE',
  CLUBS_TWO = 'CLUBS_TWO',
  CLUBS_THREE = 'CLUBS_THREE',
  CLUBS_FIVE = 'CLUBS_FIVE',
  CLUBS_SIX = 'CLUBS_SIX',
  CLUBS_SEVEN = 'CLUBS_SEVEN',
  CLUBS_EIGHT = 'CLUBS_EIGHT',
  CLUBS_NINE = 'CLUBS_NINE',
  CLUBS_TEN = 'CLUBS_TEN',
  CLUBS_JACK = 'CLUBS_JACK',
  CLUBS_QUEEN = 'CLUBS_QUEEN',
  CLUBS_KING = 'CLUBS_KING'
}

/**
 * Defines enum of Card Objects
 */
export const cssMappings = {
  //  Turn down Cards
  [Card.BLANK_CARD]: 'blank card',
  //  Spades
  [Card.SPADES_ACE]: 'spades ace',
  [Card.SPADES_TWO]: 'spades two',
  [Card.SPADES_THREE]: 'spades three',
  [Card.SPADES_FOUR]: 'spades four',
  [Card.SPADES_FIVE]: 'spades five',
  [Card.SPADES_SIX]: 'spades six',
  [Card.SPADES_SEVEN]: 'spades seven',
  [Card.SPADES_EIGHT]: 'spades eight',
  [Card.SPADES_NINE]: 'spades nine',
  [Card.SPADES_TEN]: 'spades ten',
  [Card.SPADES_JACK]: 'spades jack',
  [Card.SPADES_QUEEN]: 'spades queen',
  [Card.SPADES_KING]: 'spades king',
  // Hearts
  [Card.HEARTS_ACE]: 'hearts ace',
  [Card.HEARTS_TWO]: 'hearts two',
  [Card.HEARTS_THREE]: 'hearts three',
  [Card.HEARTS_FOUR]: 'hearts four',
  [Card.HEARTS_FIVE]: 'hearts five',
  [Card.HEARTS_SIX]: 'hearts six',
  [Card.HEARTS_SEVEN]: 'hearts seven',
  [Card.HEARTS_EIGHT]: 'hearts eight',
  [Card.HEARTS_NINE]: 'hearts nine',
  [Card.HEARTS_TEN]: 'hearts ten',
  [Card.HEARTS_JACK]: 'hearts jack',
  [Card.HEARTS_QUEEN]: 'hearts queen',
  [Card.HEARTS_KING]: 'hearts king',
  // Diamonds
  [Card.DIAMONDS_ACE]: 'diamonds ace',
  [Card.DIAMONDS_TWO]: 'diamonds two',
  [Card.DIAMONDS_THREE]: 'diamonds three',
  [Card.DIAMONDS_FOUR]: 'diamonds four',
  [Card.DIAMONDS_FIVE]: 'diamonds five',
  [Card.DIAMONDS_SIX]: 'diamonds six',
  [Card.DIAMONDS_SEVEN]: 'diamonds seven',
  [Card.DIAMONDS_EIGHT]: 'diamonds eight',
  [Card.DIAMONDS_NINE]: 'diamonds nine',
  [Card.DIAMONDS_TEN]: 'diamonds ten',
  [Card.DIAMONDS_JACK]: 'diamonds jack',
  [Card.DIAMONDS_QUEEN]: 'diamonds queen',
  [Card.DIAMONDS_KING]: 'diamonds king',
  // Clubs
  [Card.CLUBS_ACE]: 'clubs ace',
  [Card.CLUBS_TWO]: 'clubs two',
  [Card.CLUBS_THREE]: 'clubs three',
  [Card.CLUBS_FIVE]: 'clubs five',
  [Card.CLUBS_SIX]: 'clubs six',
  [Card.CLUBS_SEVEN]: 'clubs seven',
  [Card.CLUBS_EIGHT]: 'clubs eight',
  [Card.CLUBS_NINE]: 'clubs nine',
  [Card.CLUBS_TEN]: 'clubs ten',
  [Card.CLUBS_JACK]: 'clubs jack',
  [Card.CLUBS_QUEEN]: 'clubs queen',
  [Card.CLUBS_KING]: 'clubs king'
}
