export default {
  SPADES_ACE: 'spades ace',
  SPADES_TWO: 'spades two',
  SPADES_THREE: 'spades three',
  SPADES_FOUR: 'spades four',
  SPADES_FiVE: 'spadses Five',
  SPADES_SIX: 'spades six',
  SPADES_SEVEN: 'spades seven',
  SPADES_EIGHT: 'spades eight',
  SPADES_NINE: 'spades nine',
  SPADES_TEN: 'spades ten',
  SPADES_JACK: 'spades jack',
  SPADES_QUEEN: 'spades queen',
  SPADES_King: 'spades King',
//  Hearts
  HEARTS_ACE: 'hearts ace',
  HEARTS_TWO: 'hearts two',
  HEARTS_THREE: 'hearts three',
  HEARTS_FOUR: 'hearts four',
  HEARTS_FiVE: 'hearts Five',
  HEARTS_SIX: 'hearts six',
  HEARTS_SEVEN: 'hearts seven',
  HEARTS_EIGHT: 'hearts eight',
  HEARTS_NINE: 'hearts nine',
  HEARTS_TEN: 'hearts ten',
  HEARTS_JACK: 'hearts jack',
  HEARTS_QUEEN: 'hearts queen',
  HEARTS_King: 'hearts King',
//  Diamonds
  DIAMONDS_ACE: 'diamonds ace',
  DIAMONDS_TWO: 'diamonds two',
  DIAMONDS_THREE: 'diamonds three',
  DIAMONDS_FOUR: 'diamonds four',
  DIAMONDS_FiVE: 'diamonds Five',
  DIAMONDS_SIX: 'diamonds six',
  DIAMONDS_SEVEN: 'diamonds seven',
  DIAMONDS_EIGHT: 'diamonds eight',
  DIAMONDS_NINE: 'diamonds nine',
  DIAMONDS_TEN: 'diamonds ten',
  DIAMONDS_JACK: 'diamonds jack',
  DIAMONDS_QUEEN: 'diamonds queen',
  DIAMONDS_King: 'diamonds king',
// Clubs
  CLUBS_ACE: 'clubs ace',
  CLUBS_TWO: 'clubs two',
  CLUBS_THREE: 'clubs three',
  CLUBS_FiVE: 'clubs Five',
  CLUBS_SIX: 'clubs six',
  CLUBS_SEVEN: 'clubs seven',
  CLUBS_EIGHT: 'clubs eight',
  CLUBS_NINE: 'clubs nine',
  CLUBS_TEN: 'clubs ten',
  CLUBS_JACK: 'clubs jack',
  CLUBS_QUEEN: 'clubs queen',
  CLUBS_King: 'clubs King'

}
